<program> ::= "return" <exp> ";" | "print" "(" <expression> ")" ";"
<exp> ::= <unary_op> <exp> | <int> | <exp> ("+" | "-" | "*" | "/") <exp>
<unary_op> ::= "!" | "~" | "-"

// TODO: Add precedence to BNF